POST localhost:8080/api/login
Content-Type: application/json
Accept: application/json

{
    "email": "gutmann.kareem@example.org",
    "password": "password"
}

###

POST localhost:8080/api/login
Content-Type: application/json

{
    "email": "emery60@example.net",
    "password": "password"
}

###

POST localhost:8080/api/logout
Content-Type: application/json
Accept: application/json
Authorization: Bearer 4|PHDFM20PWUKbYHai3d8UM9g4xfTGjG1596EJmZn6ba93f15f

###

GET localhost:8080/api/me
Content-Type: application/json
Accept: application/json
Authorization: Bearer 3|COnEpWWs5iqjnPtXWIcjvSbeRfcYSHvA2Je6qrbH8f465086

###

GET localhost:8080/api/todos
Content-Type: application/json
Authorization: Bearer 4|PHDFM20PWUKbYHai3d8UM9g4xfTGjG1596EJmZn6ba93f15f

###

POST localhost:8080/api/todos
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|iZbWdHbtPfq9MGCrY3Wzm6OogYRD6zJfezLPNhKgb0a18e91

{
    "title": "Amazon music",
    "description": "test",
    "completed": false
}

###

GET localhost:8080/api/todos/1
Content-Type: application/json
Authorization: Bearer 2|R0HeBHaqid7XKRIEXADJtQw6l7FOs81G2CUCvopU8d17ac73

###

PUT localhost:8080/api/todos/1
Content-Type: application/json
Authorization: Bearer 5|KVffoR3JdKazObFpzSeO4UUprYOkqswAQXYDFs8rbf33ef63

{
    "title": "test put",
    "description": "test",
    "completed": false
}

###

DELETE localhost:8080/api/todos/1
Content-Type: application/json
Authorization: Bearer 11|Vx6WJYFqtOdaUQkqbGzvpFvIufeW4VHzl6beNZ7c97a28f5e

###

GET localhost:8080/api/admin/todos
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|iZbWdHbtPfq9MGCrY3Wzm6OogYRD6zJfezLPNhKgb0a18e91

###

GET localhost:8080/api/admin/todos
Content-Type: application/json
#Accept: application/json
Authorization: Bearer 2|fgJnO9E9HXrwEYi8ls1J71sCnOA7jVTyIoggB0Zra5b19d51
