POST localhost:8000/api/login
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "password"
}

###

POST localhost:8000/api/logout
Content-Type: application/json
Authorization: Bearer 13|WGlyZLNHKQP1Kc8GEJUoO0mE9kGuor6NCohyt1GY110fc80c

###

GET localhost:8000/api/me
Content-Type: application/json
Authorization: Bearer 12|m5BIeqJoL06FtSAGoJd8RgPJ1cEm2hHGYTY6Sq958b6e4fd7

###

GET localhost:8000/api/todos
Content-Type: application/json
Authorization: Bearer 11|Vx6WJYFqtOdaUQkqbGzvpFvIufeW4VHzl6beNZ7c97a28f5e

###

POST localhost:8000/api/todos
Content-Type: application/json
Authorization: Bearer 12|m5BIeqJoL06FtSAGoJd8RgPJ1cEm2hHGYTY6Sq958b6e4fd7

{
    "title": "test post",
    "description": "test",
    "completed": false
}

###

GET localhost:8000/api/todos/1
Content-Type: application/json
Authorization: Bearer 11|Vx6WJYFqtOdaUQkqbGzvpFvIufeW4VHzl6beNZ7c97a28f5e

###

PUT localhost:8000/api/todos/1
Content-Type: application/json
Authorization: Bearer 11|Vx6WJYFqtOdaUQkqbGzvpFvIufeW4VHzl6beNZ7c97a28f5e

{
    "title": "test put",
    "description": "test",
    "completed": false
}

###

DELETE localhost:8000/api/todos/1
Content-Type: application/json
Authorization: Bearer 11|Vx6WJYFqtOdaUQkqbGzvpFvIufeW4VHzl6beNZ7c97a28f5e
